# Generated by Django 3.2.8 on 2022-02-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogueApp', '0004_userlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
