# Generated by Django 3.2.8 on 2022-02-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogueApp', '0005_auto_20220202_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Subscribers',
        ),
    ]
